//! Published vectors for the relay circuit descriptor.
//!
//! # What can and cannot be published
//!
//! The sealing itself is random: a fresh nonce and a fresh encapsulation every
//! time, which is a property worth having and one that makes the output
//! unreproducible. So what is published is the two deterministic halves, which
//! is what a reimplementation actually needs to check it agrees with us:
//!
//! - the **binding**, which both sides compute and neither transmits
//! - the **key derivation** from an encapsulated secret
//!
//! `pq-vectors.txt` takes the same approach and says so: it lists the binding
//! beside each case so the halves can be checked independently.
//!
//! Verified on every test run, so the file cannot drift from the code.
//!
//! Regenerate with:
//!   cargo test -p rotelyx-crypto --test circuit_vectors -- --ignored emit

use rotelyx_crypto::circuit_binding;

const VECTORS: &str = include_str!("circuit-vectors.txt");

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex"))
        .collect()
}

/// The cases, chosen for the edges rather than for coverage.
fn cases() -> Vec<(&'static str, [u8; 32], u64)> {
    vec![
        ("all-zero-relay-at-hour-zero", [0u8; 32], 0),
        ("all-one-relay", [0xffu8; 32], 400_000),
        ("maximum-hour", [0x42u8; 32], u64::MAX),
        // An id whose tail looks like an hour. Without length prefixes this is
        // where an ambiguous binding shows itself.
        ("id-ending-in-something-hour-shaped", {
            let mut k = [0u8; 32];
            k[24..].copy_from_slice(&400_000u64.to_be_bytes());
            k
        }, 400_000),
    ]
}

#[test]
fn the_implementation_matches_the_published_vectors() {
    let mut checked = 0;
    let mut current: Option<String> = None;

    for line in VECTORS.lines() {
        let line = line.trim();
        if let Some(name) = line.strip_prefix("vector ") {
            current = Some(name.to_string());
            continue;
        }
        let Some((field, value)) = line.split_once('=') else { continue };
        if field.trim() != "binding" {
            continue;
        }
        let name = current.clone().expect("a field before any vector");
        let (_, exit_id, hour) = cases()
            .into_iter()
            .find(|(n, _, _)| *n == name)
            .unwrap_or_else(|| panic!("the file names a vector this test does not build: {name}"));

        assert_eq!(
            hex(&circuit_binding(&exit_id, hour)),
            value.trim(),
            "the binding for `{name}` does not match the published vector. \
             Either the construction changed and the file was not regenerated, \
             or somebody edited the file by hand"
        );
        checked += 1;
    }

    assert_eq!(
        checked,
        cases().len(),
        "the file does not carry every case this test builds: a vector that is \
         not published is a vector nobody outside can check against"
    );
}

/// Two different relays and hours must never produce the same binding.
///
/// This is the property length-prefixing exists for, and it is checked here
/// rather than argued in the document: a binding that two inputs share is a
/// descriptor that can be moved between them.
#[test]
fn no_two_cases_share_a_binding() {
    let mut seen: Vec<(String, String)> = Vec::new();
    for (name, id, hour) in cases() {
        let b = hex(&circuit_binding(&id, hour));
        if let Some((other, _)) = seen.iter().find(|(_, v)| *v == b) {
            panic!("`{name}` and `{other}` produce the same binding");
        }
        seen.push((name.to_string(), b));
    }

    // And the case the prefixes exist for, spelled out: an id whose tail is an
    // hour must not collide with a shorter id followed by that hour.
    let mut tail = [0u8; 32];
    tail[24..].copy_from_slice(&7u64.to_be_bytes());
    assert_ne!(
        hex(&circuit_binding(&tail, 400_000)),
        hex(&circuit_binding(&[0u8; 32], 7)),
        "an id ending in an hour collides with that hour, so the binding is \
         ambiguous and a descriptor for one relay could be read as another's"
    );
}

#[test]
#[ignore = "regenerates the published vectors, run only when the construction changes"]
fn emit() {
    let mut out = String::new();
    out.push_str("# Rotelyx relay circuit descriptor, test vectors\n");
    out.push_str("# Generated by `cargo test -p rotelyx-crypto --test circuit_vectors -- --ignored emit`\n");
    out.push_str("# Specification: docs/RELAY-CHAINING.md section 4.2\n");
    out.push_str("#\n");
    out.push_str("# binding = be64(len(LABEL)) || LABEL\n");
    out.push_str("#         || be64(len(exit_id)) || exit_id\n");
    out.push_str("#         || be64(hour)\n");
    out.push_str("# LABEL   = \"rotelyx relay circuit v1\"\n");
    out.push_str("#\n");
    out.push_str("# The sealing itself is not here and cannot be: the nonce and the\n");
    out.push_str("# encapsulation are random every time. What a reimplementation checks is\n");
    out.push_str("# this and the key derivation, which is BLAKE3 derive_key under the same\n");
    out.push_str("# context string over the encapsulated secret.\n");

    for (name, id, hour) in cases() {
        out.push_str(&format!("vector {name}\n"));
        out.push_str(&format!("  exit_id = {}\n", hex(&id)));
        out.push_str(&format!("  hour    = {hour}\n"));
        out.push_str(&format!("  binding = {}\n", hex(&circuit_binding(&id, hour))));
    }

    std::fs::write(
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/circuit-vectors.txt"),
        &out,
    )
    .expect("write");
    println!("wrote {} vectors", cases().len());
    let _ = unhex("00");
}
