//! Every client in this repository is checked against the wire the server
//! writes down, rather than against its own idea of it.
//!
//! # The defect this exists to make impossible
//!
//! One protocol had four client implementations: the Rust crate the desktop
//! uses, `site/chat.html`, the phone's Dart, and the server's own tests. Each
//! wrote down what it believed the server sends. **Two of them were wrong in the
//! same way**, and independently: the server renames `OverQuota` to `overquota`,
//! both guessed `overQuota` from the Rust variant name, and in both a refused
//! deposit therefore matched no case, fell through a `switch` with no default,
//! and looked to the sender exactly like an accepted one. A message that was
//! never stored showed as sent.
//!
//! Both had a test for it. Both tests fed the client a string that client had
//! produced itself, so each confirmed it could read its own handwriting.
//!
//! That is not a mistake anybody made twice by being careless. It is what
//! happens when a wire is **described** in several places instead of being
//! **written down once and read**. So the server writes `docs/MAILBOX-WIRE.md`
//! from its own serialiser, and this file checks the clients against that.
//!
//! # What it deliberately does not do
//!
//! It does not parse JavaScript or Dart. It looks for the op names as literal
//! strings, which is crude and is the right kind of crude: a false positive
//! costs somebody five minutes, and a false negative ships a client that cannot
//! hear a refusal.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("workspace root")
        .to_path_buf()
}

/// The ops the server sends, read out of the document the server generates.
fn server_replies(root: &Path) -> BTreeSet<String> {
    let path = root.join("docs/MAILBOX-WIRE.md");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "reading {}: {e}. It is generated by the mailbox server's own tests: \
             `cargo test -p rotelyx-mailbox-server written_down`",
            path.display()
        )
    });

    // The table rows, which are the authority. `| `op` | `{json}` |`
    let mut ops = BTreeSet::new();
    for line in text.lines() {
        let line = line.trim();
        if !line.starts_with("| `") {
            continue;
        }
        if let Some(rest) = line.strip_prefix("| `") {
            if let Some(end) = rest.find('`') {
                ops.insert(rest[..end].to_string());
            }
        }
    }
    assert!(
        ops.len() >= 6,
        "the wire document lists {} replies, which is too few to believe. If the \
         format changed, this reader has to change with it",
        ops.len()
    );
    ops
}

/// Replies that say a request **failed**.
///
/// A client may ignore `ready` or `dropped` and be no worse for it. Ignoring one
/// of these is how a refusal becomes a success, which is the failure this whole
/// file is about.
const REFUSALS: &[&str] = &["error", "overquota"];

#[test]
fn the_browser_handles_every_refusal_the_server_can_send() {
    let root = workspace_root();
    let ops = server_replies(&root);

    let page = root.join("site/chat.html");
    let text = std::fs::read_to_string(&page).expect("site/chat.html is readable");

    let mut missing = Vec::new();
    for op in REFUSALS {
        assert!(
            ops.contains(*op),
            "`{op}` is not in the wire document any more, so this list is stale"
        );
        // Either quoting style, because a page is not a Rust file.
        let found = text.contains(&format!("'{op}'")) || text.contains(&format!("\"{op}\""));
        if !found {
            missing.push(*op);
        }
    }

    assert!(
        missing.is_empty(),
        "site/chat.html does not handle {missing:?}, which the server sends to say \
         a request failed. A refusal nobody handles is a refusal that looks like \
         success: that is exactly how `overquota` lost messages in two clients. \
         The names come from docs/MAILBOX-WIRE.md, which the server generates."
    );
}

/// The browser must not be reading an op the server does not send.
///
/// The other direction of the same defect: a client waiting for a name nobody
/// emits waits for ever, and `overQuota` was that too.
#[test]
fn the_browser_reads_no_op_the_server_never_sends() {
    let root = workspace_root();
    let ops = server_replies(&root);

    let page = root.join("site/chat.html");
    let text = std::fs::read_to_string(&page).expect("site/chat.html is readable");

    // Every `reply.op === '...'` the page compares against.
    let mut invented = Vec::new();
    for (line_number, line) in text.lines().enumerate() {
        let Some(at) = line.find("reply.op === '") else {
            continue;
        };
        let rest = &line[at + "reply.op === '".len()..];
        let Some(end) = rest.find('\'') else { continue };
        let op = &rest[..end];
        if !ops.contains(op) {
            invented.push(format!("line {}: `{op}`", line_number + 1));
        }
    }

    assert!(
        invented.is_empty(),
        "site/chat.html compares against ops the server does not send: {invented:?}. \
         A client waiting for a name nobody emits waits for ever. The names the \
         server does send are in docs/MAILBOX-WIRE.md."
    );
}

/// The Rust client's own frames, against the same document.
#[test]
fn the_rust_client_sends_ops_the_server_accepts() {
    let root = workspace_root();
    let path = root.join("crates/rotelyx-mailbox-client/src/lib.rs");
    let text = std::fs::read_to_string(&path).expect("the client is readable");

    let document = std::fs::read_to_string(root.join("docs/MAILBOX-WIRE.md"))
        .expect("the wire document exists");

    // The request ops, from the bullet list the server writes.
    let accepted: BTreeSet<&str> = document
        .lines()
        .filter_map(|l| l.trim().strip_prefix("- `"))
        .filter_map(|l| l.strip_suffix('`'))
        .collect();
    assert!(
        accepted.len() >= 4,
        "the wire document lists {} requests, too few to check against",
        accepted.len()
    );

    // Renames written by hand are the ones worth checking. A variant that takes
    // the container's `rename_all` is only right by luck, and this repository
    // has the scar to prove it: the client's enums said `camelCase` where the
    // server says `lowercase`, which agrees on every one-word name and differs
    // on every other.
    //
    // Told apart by indentation, because a variant sits at four spaces inside
    // the enum and a field sits at eight inside the variant. Crude, and correct
    // for this file. The first version of this check did not tell them apart
    // and reported `maxFanout`, a field, as an op the server does not send.
    for line in text.lines() {
        let Some(at) = line.find("#[serde(rename = \"") else {
            continue;
        };
        let rest = &line[at + "#[serde(rename = \"".len()..];
        let Some(end) = rest.find('"') else { continue };
        let name = &rest[..end];
        let indent = line.len() - line.trim_start().len();

        if indent <= 4 {
            assert!(
                accepted.contains(name) || document.contains(&format!("| `{name}` |")),
                "the client renames a frame to `{name}`, which the server neither \
                 accepts nor sends. See docs/MAILBOX-WIRE.md."
            );
        } else {
            // A field. It has to appear as a key in one of the shapes the
            // server writes, or the client is reading something nobody sends.
            assert!(
                document.contains(&format!("\"{name}\":")),
                "the client reads a field `{name}`, which appears in no reply the \
                 server sends. That is the other half of the same defect: a name \
                 nobody emits is a value that never arrives. See \
                 docs/MAILBOX-WIRE.md."
            );
        }
    }
}
